# Generated by Django 3.2.7 on 2021-09-25 08:23

import diary.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_page_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='score',
            field=models.IntegerField(validators=[diary.validators.validate_score]),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=50, validators=[diary.validators.validate_no_hash]),
        ),
    ]
