# Generated by Django 3.2.7 on 2021-09-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
