# Generated by Django 3.2.7 on 2021-09-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userplate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
