# Generated by Django 3.2.7 on 2021-10-01 09:44

from django.db import migrations, models
import userplate.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userplate', '0002_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용 중인 닉네임입니다.'}, max_length=10, null=True, unique=True, validators=[userplate.validators.validate_no_special_characters]),
        ),
    ]
