# Generated by Django 3.2.7 on 2021-09-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='point',
            field=models.IntegerField(choices=[('1', '★'), ('2', '★★'), ('3', '★★★'), ('4', '★★★★'), ('5', '★★★★★')], default=None),
        ),
    ]
